require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SerialNumbersController do

  # This should return the minimal set of attributes required to create a valid
  # SerialNumber. As you add validations to SerialNumber, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SerialNumbersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all serial_numbers as @serial_numbers" do
      serial_number = SerialNumber.create! valid_attributes
      get :index, {}, valid_session
      assigns(:serial_numbers).should eq([serial_number])
    end
  end

  describe "GET show" do
    it "assigns the requested serial_number as @serial_number" do
      serial_number = SerialNumber.create! valid_attributes
      get :show, {:id => serial_number.to_param}, valid_session
      assigns(:serial_number).should eq(serial_number)
    end
  end

  describe "GET new" do
    it "assigns a new serial_number as @serial_number" do
      get :new, {}, valid_session
      assigns(:serial_number).should be_a_new(SerialNumber)
    end
  end

  describe "GET edit" do
    it "assigns the requested serial_number as @serial_number" do
      serial_number = SerialNumber.create! valid_attributes
      get :edit, {:id => serial_number.to_param}, valid_session
      assigns(:serial_number).should eq(serial_number)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SerialNumber" do
        expect {
          post :create, {:serial_number => valid_attributes}, valid_session
        }.to change(SerialNumber, :count).by(1)
      end

      it "assigns a newly created serial_number as @serial_number" do
        post :create, {:serial_number => valid_attributes}, valid_session
        assigns(:serial_number).should be_a(SerialNumber)
        assigns(:serial_number).should be_persisted
      end

      it "redirects to the created serial_number" do
        post :create, {:serial_number => valid_attributes}, valid_session
        response.should redirect_to(SerialNumber.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serial_number as @serial_number" do
        # Trigger the behavior that occurs when invalid params are submitted
        SerialNumber.any_instance.stub(:save).and_return(false)
        post :create, {:serial_number => {}}, valid_session
        assigns(:serial_number).should be_a_new(SerialNumber)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SerialNumber.any_instance.stub(:save).and_return(false)
        post :create, {:serial_number => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serial_number" do
        serial_number = SerialNumber.create! valid_attributes
        # Assuming there are no other serial_numbers in the database, this
        # specifies that the SerialNumber created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SerialNumber.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => serial_number.to_param, :serial_number => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested serial_number as @serial_number" do
        serial_number = SerialNumber.create! valid_attributes
        put :update, {:id => serial_number.to_param, :serial_number => valid_attributes}, valid_session
        assigns(:serial_number).should eq(serial_number)
      end

      it "redirects to the serial_number" do
        serial_number = SerialNumber.create! valid_attributes
        put :update, {:id => serial_number.to_param, :serial_number => valid_attributes}, valid_session
        response.should redirect_to(serial_number)
      end
    end

    describe "with invalid params" do
      it "assigns the serial_number as @serial_number" do
        serial_number = SerialNumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SerialNumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => serial_number.to_param, :serial_number => {}}, valid_session
        assigns(:serial_number).should eq(serial_number)
      end

      it "re-renders the 'edit' template" do
        serial_number = SerialNumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SerialNumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => serial_number.to_param, :serial_number => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serial_number" do
      serial_number = SerialNumber.create! valid_attributes
      expect {
        delete :destroy, {:id => serial_number.to_param}, valid_session
      }.to change(SerialNumber, :count).by(-1)
    end

    it "redirects to the serial_numbers list" do
      serial_number = SerialNumber.create! valid_attributes
      delete :destroy, {:id => serial_number.to_param}, valid_session
      response.should redirect_to(serial_numbers_url)
    end
  end

end
